apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: appache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-yment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 5
    - type: Resource
      resource:
        name: requests
        target:
          type: AverageValue
          averageValue: "200Mi"
    - type: Resource
      




