kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager-rolebinding
  namespace: apache
subjects:
  - kind: ServiceAccount
    name: apache-manager
    namespace: apache
    
